### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by GHT0320** [TRI-ML/PF-Track#18]
When I run the visualization code with the command “python tools/video_demo/cam_demo.py --data_infos_path ./data/nuscenes/tracking_forecasting-mini_infos_val.pkl --result results.json --show-dir ./work_dirs/visualizations/”, I encountered the following error:

  
Traceback (most recent call last):
  File "tools/cam_demo.py", line 260, in <module>
    make_videos(show_dir, fig_names, 'video.mp4', show_dir)
  File "tools/cam_demo.py", line 213, in make_videos
    writer.append_data(cv2.resize(imageio.imread(im), (4000, 2800)))
  File "/home/guohaotian/anaconda3/envs/PFTrack/lib/python3.8/site-packages/imageio/v2.py", line 226, in append_data
    return self.instance.write(im, **self.write_args)
  File "/home/guohaotian/anaconda3/envs/PFTrack/lib/python3.8/site-packages/imageio/plugins/tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
TypeError: write() got an unexpected keyword argument 'fps'

**Comment by GHT0320** [comment]
but now，I encountered the following error：Traceback (most recent call last):
  File "tools/bev.py", line 199, in <module>
    main()
  File "tools/bev.py", line 70, in main
    raw_data = dataset[data_info_idx]
  File "/home/guohaotian/PF-Track-main/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 357, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/guohaotian/PF-Track-main/projects/tracking_plugin/datasets/nuscenes_tracking_dataset.py", line 313, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/guohaotian/anaconda3/envs/PFTrack/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/guohaotian/PF-Track-main/projects/tracking_plugin/datasets/pipelines/pipeline.py", line 470, in __call__
    results = self._load_forecasting(results)
  File "/home/guohaotian/PF-Track-main/projects/tracking_plugin/datasets/pipelines/pipeline.py", line 373, in _load_forecasting
    results['gt_forecasting_locs'] = results['ann_info']['gt_forecasting_locs']
KeyError: 'gt_forecasting_locs'
  0%|

**Comment by ziqipang** [comment]
@GHT0320 Downgrade your imageio version, check https://github.com/OpenTalker/SadTalker/issues/276

**Comment by ziqipang** [comment]
@GHT0320 If you don't have further questions, please kindly close the issue.
