### ISSUE TITLE
TypeError: cannot pickle 'dict_keys' object

### ISSUE THREAD

**Issue by wzh506** [TRI-ML/PF-Track#38]
Thanks for your great work!But I have a small problem with the implementation.
When I load the dataset,I find:
Traceback (most recent call last):
  File "tools/train.py", line 260, in <module>
    main()
  File "tools/train.py", line 249, in main
    train_model(
  File "/home/wzh/study/github/3Dobjectdetection/Sparse4D/mmdetection3d/mmdet3d/apis/train.py", line 64, in train_model
    train_detector(
  File "/home/wzh/study/github/3Dobjectdetection/PF-Track/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wzh/study/github/3Dobjectdetection/Sparse4D/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wzh/study/github/3Dobjectdetection/Sparse4D/mmcv/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/wzh/anaconda3/envs/sparse4d/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'dict_keys' object
I download the full dataset and the data annotation files, So could someone help me?

**Comment by ziqipang** [comment]
@wzh506 My guess is that you are using some newer version of mmdet3d?
