### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by wzh506** [TRI-ML/PF-Track#39]
Thanks for your great work!But I have a little question about the visualization:
I use:

**python tools/video_demo/bev.py ./projects/configs/tracking/petr/f3_q5_800x320.py --result ./work_dir/f3_all/track_no_ext/results_nusc_tracking.json --show-dir ./work_dir/visualizations/**

**(sparse4d) (base) wzh@wzh-pc:~/study/github/3Dobjectdetection/PF-Track$ python tools/video_demo/bev.py ./projects/configs/tracking/petr/f3_q5_800x320.py --result ./work_dir/f3_all/track_no_ext/results_nusc_tracking.json --show-dir ./work_dir/visualizations/
projects
  0%|                                                                                                          | 0/6019 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/video_demo/bev.py", line 197, in <module>
    main()
  File "tools/video_demo/bev.py", line 66, in main
    data_info_idx = data_info_sample_tokens.index(sample_token)
ValueError: '30e55a3ec6184d8cb1944b39ba19d622' is not in list**

I have downloaded fulldataset (only trainval, without test) and mini dataset,could yuo help me?

**Comment by ziqipang** [comment]
@wzh506 Could you check if you nuscenes have this sample?
